// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer DIRECT_URL for migrations; fall back so `prisma generate` works
    // on Vercel when only DATABASE_URL is configured.
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
});
